In [3]:
from pathlib import Path
import pandas as pd
from narwhals import DataFrame

path_to_csv = Path("../datasets/rnc_dataset_markup.csv")

In [4]:
try:
    df = pd.read_csv(path_to_csv, sep=';', on_bad_lines='skip')
except FileNotFoundError as e:
    print(f"Error: {e}, try to specify path correct.")

In [5]:
df = df.drop(
    columns=["itemId", "split", "targetDetectedMcIds", "targetSplitMcIds", "caseType"]
)

In [6]:
df.tail()

,sourceMcId,sourceMcTitle,description,shouldSplit
2475,101,Ремонт квартир и домов под ключ,Здраствуйте! Облицовка кафелем устройство ГКЛ...,True
2476,101,Ремонт квартир и домов под ключ,Комплексный ремонт квартир \n\nБЕЗ ВЫХОДНЫХ\n\...,False
2477,101,Ремонт квартир и домов под ключ,Ремонт ванных комнат под ключ в Светлогорске. ...,False
2478,101,Ремонт квартир и домов под ключ,"Ремонт квартир, офисов. От штукатурки до плинт...",False
2479,101,Ремонт квартир и домов под ключ,Все види строительство и ремонт\nЦены договорные,False

In [8]:
from utils.description_features_utils import (
    has_bull_markers,
    slash_counter,
    has_slash,
    paragraph_counter,
    word_separately_in_desc,
    count_the_occurrence_of_words_for_separation,
    turkney_count,
)


def features_from_description(df: DataFrame) -> dict:
    desc = df["description"]
    return dict(
        desc_words_count=len(desc.split()),
        desc_length=len(desc),
        has_bull_markers=has_bull_markers(desc),
        has_slashes=has_slash(desc),
        slash_counted=slash_counter(desc),
        paragraph_counted=paragraph_counter(desc),
        turnkey_count=turkney_count(desc),
    )


features_desc = df.apply(features_from_description, axis=1)

df_with_desc_features = pd.concat((df, pd.DataFrame(features_desc.tolist())), axis=1)

In [9]:
from numpy._typing import ArrayLike
##### tokenizer & embeddings block
import torch
from torch import nn
from sentence_transformers import SentenceTransformer

bert_model = SentenceTransformer('cointegrated/rubert-tiny2')

enc = bert_model.encode(sentences=["привет, мир", "я на луне"])

print(type(enc).__name__, len(enc))

def row_to_embeds(df_row, /, bert_model_=bert_model) -> ArrayLike:
    title = df_row["sourceMcTitle"]
    desc = df_row["description"]
    sep = "[SEP]"
    sentence = [f"{title + sep + desc}"]
    return bert_model_.encode(sentences=sentence)





import numpy as np

embeds = [row_to_embeds(df.iloc[i], bert_model) for i in range(len(df))]
mtrx = np.vstack(embeds)
df_with_embeds = pd.DataFrame(data=mtrx).add_prefix("embeds")

/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 55/55 [00:00<00:00, 7969.83it/s]
BertModel LOAD REPORT from: cointegrated/rubert-tiny2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
bert.embeddings.position_ids               | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

ndarray 2

In [58]:

from scipy.spatial.distance import pdist
import re
from random import randint

def l2_mean(input_):
    dist = pdist(input_, metric="euclidean")
    return np.mean(dist)

def sentences_to_embeds_with_l2(df_):
    desc = df_["description"]
    text = str(desc).replace("\\r\\n", "\n").replace("\\n", "\n").replace("\r", "\n")
    sentences = [p.strip() for p in re.split(r'(?<=[.!?])\s+|\n+', text) if p.strip()]
    if len(sentences) < 2:
        return 0.0
    sentence_vectors = bert_model.encode(sentences)
    l2mean = l2_mean(input_=sentence_vectors)
    return l2mean

sent_embeddings_with_l2 = [sentences_to_embeds_with_l2(df.iloc[i]) for i in range(len(df))]

In [92]:
df_l2_embeds = pd.DataFrame({"embeds_l2":sent_embeddings_with_l2})

In [37]:


cov_m = np.cov(mtrx, rowvar=False) # covariance matrix
L, M = np.linalg.eigh(cov_m) # computing eigenvectors
print(*sorted(L, reverse=True), sep="\n")

0.04541116866835409
0.022480200479965847
0.012276932057143522
0.010088075381152292
0.007948909744582332
0.005436520898988183
0.005315522949871401
0.004789539677445479
0.004435420639964932
0.004005102751642469
0.0034115428881490556
0.003246503177387544
0.0031906786982448215
0.0029537534817890504
0.0028181755746184314
0.0025535416849112543
0.002461687548436408
0.002364754431106175
0.0022685836761005213
0.0021348480304687564
0.002061184882312692
0.0019959351853802406
0.0018837717885431618
0.0018638942674142327
0.0017606474770289389
0.0016081673505631158
0.0015642821861159772
0.0014968659197215804
0.0014181962974526977
0.0013948680395698097
0.0012664617654386064
0.0012584251967513276
0.0012021198162557143
0.0011676996707652466
0.0011523507832905885
0.001111667977050824
0.0010668965093472951
0.001007449624348607
0.0010027048233268554
0.0009640130260017287
0.0009308483627505675
0.0009231007895779403
0.0008793211402901715
0.0008665421244250174
0.0008286873067964991
0.0008157312883533347
0.0008121639442253027
0.0007839602603033656
0.0007689404683080109
0.000745751137649278
0.0007340089182002832
0.0007132658630806251
0.0006833030980659244
0.0006632493799892913
0.0006453980763126382
0.0006447149080659344
0.0006249961427061197
0.0006222257195152713
0.0006096268742669812
0.0005942927281910379
0.0005811167834091268
0.000569402122423166
0.0005615835128108487
0.0005590267289584636
0.000545507864420642
0.0005303053024100499
0.000517905942256501
0.0005069161477142317
0.0004879537765478081
0.00048088134312373283
0.00047034775081363867
0.00046483577887449537
0.00044387719290268836
0.00044258372546096347
0.0004323719889892806
0.00042522491966306953
0.0004212338592342569
0.0004117826092081084
0.0004005994716406205
0.00039781593341869416
0.00038953312357284045
0.0003841411142453988
0.00037805971585367574
0.000366477058638594
0.000360573653151232
0.00035212599483880065
0.000346206337270242
0.00033378648534776293
0.0003331908037456235
0.000325417600950016
0.0003245578864878761
0.00031700863065549573
0.0003100540151823523
0.000303667261682362
0.00029659152480481215
0.00029167846736910167
0.00028559586840413905
0.0002812327647403273
0.00027791204712645216
0.0002770134508814143
0.00027158147610416387
0.0002618889977025136
0.0002600000300645057
0.00025280613718329755
0.0002513259600670362
0.0002496869252764606
0.00024405536433563937
0.0002336554002319257
0.00023240093601978854
0.00022846218566947559
0.00022540454838892838
0.00022116468855674885
0.00021896564188146627
0.00021390064184220406
0.0002132082503311629
0.00020849310353407855
0.00020410779318097135
0.00020243802899328964
0.00019853071010970938
0.00019465714866607168
0.0001921954596405924
0.00018995055035208894
0.00018660314813337872
0.0001808223853770291
0.0001793892082658337
0.0001736206459394957
0.00017010724865506677
0.0001659770725066843
0.00016561089168555865
0.00016183705911978292
0.00015902341332516394
0.00015589167943398814
0.0001514866823988266
0.00015117183917928568
0.0001481171385775296
0.00014267841096685406
0.00014189428622240162
0.0001394438862226255
0.00013732663929414156
0.00013551374051585372
0.0001338006162115562
0.000132818138130409
0.00013094444180704844
0.000128324469160525
0.00012618977749376956
0.0001206012079466639
0.00011926520264348332
0.00011658522097479267
0.00011488024063847587
0.00011320228513161979
0.00010727031949643237
0.0001057023487790897
0.00010358948610185381
0.00010254674599549182
0.00010018534824546728
9.823022484517991e-05
9.770626681850063e-05
9.704955342945276e-05
9.465093458729374e-05
9.287855462491922e-05
9.135866137168482e-05
9.012480544955183e-05
8.811673285662622e-05
8.621111874953964e-05
8.478598945081629e-05
8.352963530209723e-05
8.315713914155925e-05
8.234933157697462e-05
7.862347877949273e-05
7.742642656917976e-05
7.670484368397113e-05
7.5310347117807e-05
7.174669526422602e-05
7.066524860526814e-05
6.991210457626959e-05
6.927081127350589e-05
6.869004738695002e-05
6.755685254528827e-05
6.549825460325494e-05
6.242112668216787e-05
6.209344211513975e-05
6.162496821470975e-05
5.973471184557972e-05
5.8247999289987495e-05
5.728510356585464e-05
5.601195066949873e-05
5.472768856066025e-05
5.373828215975207e-05
5.216559509169984e-05
5.1751717532721275e-05
5.0583975063748046e-05
4.873337832132332e-05
4.838567394949886e-05
4.623742646130971e-05
4.517309287268494e-05
4.489429096958535e-05
4.4002476279277176e-05
4.299166039925923e-05
4.2620579882967235e-05
4.189944671991629e-05
4.0975115140138905e-05
4.0202884370186436e-05
3.903562351627174e-05
3.889071876720234e-05
3.859140947670787e-05
3.744789811286337e-05
3.6903182651395726e-05
3.617720566420466e-05
3.546218876835308e-05
3.4516253258925265e-05
3.402479569552439e-05
3.358498440011129e-05
3.162706531180656e-05
3.144464847984752e-05
3.0046230191561186e-05
2.992791879663652e-05
2.8843208976352155e-05
2.8591355451692685e-05
2.8253610762762202e-05
2.8021006329205225e-05
2.752359784669106e-05
2.7188468527376924e-05
2.6496391121703847e-05
2.5827103431875696e-05
2.554718260227591e-05
2.5172749958942596e-05
2.4794297587534666e-05
2.4354443821918803e-05
2.3557376459108683e-05
2.333166346533104e-05
2.324457260696419e-05
2.2840715278303426e-05
2.192940726378109e-05
2.161030463461857e-05
2.1575925861395817e-05
2.134927781555127e-05
2.0622669997137353e-05
2.0415917832204292e-05
1.9734043015175397e-05
1.9109533260769577e-05
1.905271839981724e-05
1.8302088168129802e-05
1.815495742611566e-05
1.788088075435676e-05
1.755393142657402e-05
1.709777921876266e-05
1.6605929170958146e-05
1.6403343901933703e-05
1.5970484763052035e-05
1.5770079659044592e-05
1.5585871364274535e-05
1.5465914448673527e-05
1.4998217585199523e-05
1.4777802113852654e-05
1.4498024331117608e-05
1.4196200139057041e-05
1.3865776350727342e-05
1.3814836899373595e-05
1.3683254850351664e-05
1.3302503969155588e-05
1.3096835950480788e-05
1.271790232711949e-05
1.2550861051904817e-05
1.2356927857320861e-05
1.184418043642801e-05
1.1804114517173812e-05
1.1556688417754936e-05
1.1363488283697066e-05
1.1252461112180321e-05
1.0965539442133238e-05
1.0791591977517718e-05
1.0362201974138657e-05
1.01663380370484e-05
1.008847159806653e-05
9.86190312908495e-06
9.631641455973002e-06
9.531677034615437e-06
9.454283762377654e-06
9.16627599933215e-06
8.791685020328386e-06
8.513187768909465e-06
8.310121304121672e-06
8.199024301440852e-06
8.02939080922085e-06
7.919416944675095e-06
7.846831555253535e-06
7.757369409980535e-06
7.349106413140393e-06
7.16372938741396e-06
6.9798363365251885e-06
6.914372592806632e-06
6.75569614062669e-06
6.566503741289093e-06
6.482805575874627e-06
6.455836485029389e-06
6.1500860601133055e-06
6.053071830809947e-06
5.9753356101309636e-06
5.913173568626048e-06
5.678890409835273e-06
5.513893481595648e-06
5.430479204517165e-06
5.1650553439580055e-06
5.1398648404588005e-06
5.02796031768637e-06
4.954939536600862e-06
4.820313490300177e-06
4.7148823726667974e-06
4.374069060866543e-06
4.185798626184816e-06
3.837098037869495e-06
1.5718374859014264e-11

In [55]:
from random import randint


def vectors_for_title_and_description(df_row, /, bert_model_=bert_model) -> tuple[ArrayLike, ...]:
    desc, title = df_row["description"], df_row["sourceMcTitle"]
    vectors = bert_model_.encode(sentences=[desc, title])
    return vectors[0], vectors[1]

vectors = vectors_for_title_and_description(df.iloc[randint(1, len(df))])

In [58]:
# L2-Norm as feature block
from numpy import linalg

vectors_from_df = [vectors_for_title_and_description(df.iloc[i]) for i in range(len(df))]

In [95]:
df_final = pd.concat([
      df_with_desc_features.reset_index(drop=True),
      df_l2_embeds.reset_index(drop=True),
      df_with_embeds.reset_index(drop=True)
  ], axis=1)

df_final.head()

,sourceMcId,sourceMcTitle,description,shouldSplit,desc_words_count,desc_length,has_bull_markers,has_slashes,slash_counted,paragraph_counted,...,embeds302,embeds303,embeds304,embeds305,embeds306,embeds307,embeds308,embeds309,embeds310,embeds311
0,101,Ремонт квартир и домов под ключ,"Всё виды строительных работ\r\nКачественно, в ...",False,13,85,False,False,0,1,...,0.061496,0.058535,0.019343,0.048706,0.011362,-0.047822,-0.033475,-0.017282,0.071151,-0.023715
1,101,Ремонт квартир и домов под ключ,Профессионально и качественно сделаем ремонт к...,False,107,803,True,False,0,19,...,0.082723,0.043011,0.092585,0.007061,-0.059490,-0.043415,-0.071917,0.053794,0.034265,-0.044075
2,101,Ремонт квартир и домов под ключ,"ремонт квартир, ванной комнате , балкон",False,6,39,False,False,0,0,...,0.080913,0.052698,0.105720,-0.013622,-0.048646,-0.049319,-0.041059,-0.001585,0.036794,-0.034914
3,101,Ремонт квартир и домов под ключ,ЗBОНИТЕ KОHСУЛЬТАЦИЯ БЕCПЛАTНAЯ ПO ТУЛЬСKOЙ ОБ...,True,169,1247,True,True,1,32,...,0.075075,-0.037641,0.001230,0.037845,-0.042515,-0.034750,0.004734,0.057284,0.108178,-0.076892
4,101,Ремонт квартир и домов под ключ,Ремонт квартир любой сложности. Квартиры под к...,False,26,181,False,False,0,0,...,0.072242,0.014644,0.031661,0.029496,-0.020382,-0.030702,0.009245,0.003996,0.094669,-0.075401

In [78]:
print(
    f"Random should split string for repr: \n\n {df_with_desc_features.iloc[1].to_string()}"
)

Random should split string for repr:

 sourceMcId                                                         101
sourceMcTitle                          Ремонт квартир и домов под ключ
description          Профессионально и качественно сделаем ремонт к...
shouldSplit                                                      False
desc_words_count                                                   107
desc_length                                                        803
has_bull_markers                                                  True
has_slashes                                                      False
slash_counted                                                        0
paragraph_counted                                                   19
turnkey_count                                                        1

In [102]:
from sklearn.model_selection import train_test_split

X = df_final.drop(columns=["shouldSplit", "sourceMcTitle", "description"])
y = df_final["shouldSplit"]

X_train, X_holdout, y_train, y_holdout = train_test_split(
    X, y, test_size=0.15, random_state=45, shuffle=True, stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_holdout,
    y_holdout,
    test_size=0.5,
    random_state=52,
    shuffle=True,
    stratify=y_holdout,
)

In [111]:
from sklearn.preprocessing import StandardScaler

X_numeric = X_train.select_dtypes(include=[np.number]).fillna(0)
X_array = X_numeric.values.astype('float64')
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_numeric)
x_train_mtrx_cov = np.cov(X_scaled, rowvar=False)
L, M = np.linalg.eigh(x_train_mtrx_cov)

print(*sorted(L, reverse=True), sep="\n")

53.40221927283753
28.077397216647867
16.210160245125536
14.819586380676888
10.95471517097209
8.332426652279594
7.6173263162191995
7.146613663914597
6.5918833499577465
6.027776874888011
5.434231312706634
5.06571887382519
4.856775739472505
4.67586032822037
4.209743626764211
3.8884979665412205
3.777304541976035
3.619058175114896
3.5177096584616128
3.264362683465499
3.169368162410378
3.040242127033606
2.8943644739093664
2.8156954809863803
2.7451219857209437
2.537437081140393
2.3205819292447574
2.2657564809372506
2.217100290521485
2.1310865959663197
2.0907853964760106
1.9818568123869844
1.9448240691227652
1.8735549350570586
1.7553344175882386
1.7361456840512501
1.720296308435401
1.67294429219794
1.6016404366089665
1.5225002840339084
1.435789438019721
1.417040458743697
1.4083457798308936
1.336909130844796
1.3100427637800875
1.2835257798485422
1.2462066671591074
1.229938956997265
1.2127570222588335
1.1706385364575693
1.1478884990604972
1.1250437647349698
1.102694508387885
1.0586626646294681
1.0416949469344912
1.0297446241900312
1.0141493771857364
0.9889013174854098
0.9818942857812557
0.9678803954178637
0.938446336421982
0.9060338525663739
0.8766599609839054
0.8656994224422928
0.8603321764010043
0.8461171826626659
0.8117651092606357
0.7979997573065261
0.7912224606796706
0.7712107202296924
0.7491127164212618
0.726245994708435
0.7154571325120836
0.6996250940584833
0.6942732920246438
0.6780890325547166
0.6649859321616558
0.6573441496882104
0.6478897704675106
0.63149067702369
0.625491372857945
0.605814899182583
0.5923868602720955
0.588130632896375
0.5692352585042358
0.5669533920658246
0.5506856864214588
0.5482677223819523
0.535598374087871
0.5218173332729573
0.5153045363919595
0.5083411093405606
0.5065557486759782
0.49127337065013016
0.4894634057680329
0.4734952093229911
0.46441754487391274
0.45120945311088384
0.4424572233087432
0.43306118518652736
0.42682930577236666
0.4170302590492554
0.4091823053755275
0.4059047193132853
0.39714622994186927
0.3866630354258757
0.3815163719124864
0.37631667646294686
0.3711651066448725
0.36098552191153904
0.3576908503677676
0.35425430998649204
0.34934059905530945
0.34402630664104616
0.33374396485966784
0.32927079689528127
0.32661293298312305
0.32080775103182807
0.31207958870784264
0.30870029253450587
0.3012875501771139
0.29918557764600834
0.2933190244041181
0.29040029784356286
0.2886880363565291
0.2804116814871767
0.27616535830616307
0.27200215951651185
0.26898122536464447
0.2636369793369493
0.2591120993513025
0.2566633832646931
0.2500815783894743
0.23822222603321588
0.23552414907910396
0.23256685646882574
0.22606423606840817
0.22398040167433975
0.2198240374161577
0.21656499918242778
0.2118489330383311
0.21103953642016682
0.20670918247476663
0.20212869710602538
0.1986846725532472
0.19729006934073615
0.193591604755118
0.18991921428353548
0.18765805392589682
0.18371377546005654
0.17788445398856498
0.17682638852698399
0.1736078417078644
0.17060008512726374
0.16907399979102883
0.15963638657351725
0.15816037338654293
0.15536081051331613
0.14963300863805662
0.148213240168019
0.1454690600339126
0.14413831739819769
0.1406101822467244
0.1400942276125015
0.13593183232866665
0.13475966605861464
0.1338184030151355
0.1294425867711584
0.1289978094702724
0.12502652130809383
0.12188489475142308
0.12096811024450783
0.11977295346397122
0.1187768349705893
0.1149225140439265
0.1142335333008377
0.11133451959006416
0.11089613850164722
0.10820881234829136
0.1032868111963598
0.1004913257757836
0.09881300455941726
0.09784403577245278
0.09479855924238031
0.09125136996937125
0.08979114852653743
0.08791418664227205
0.08725761983721682
0.08657638703036882
0.08326066235806838
0.08214462619597605
0.08051555596517998
0.07743248808529522
0.07649521027032799
0.07511735406578546
0.0742811244149363
0.07305766730125844
0.07142412374671525
0.06796550793195293
0.06721778692171622
0.06610745552073018
0.06574342051970015
0.06453438733560889
0.06295183990111583
0.062140412754156896
0.061626835335618114
0.05943367320271887
0.05766065738434682
0.056280484415456945
0.05518036295899499
0.05469324363501238
0.05331288372787718
0.0521503225088246
0.05171044345484171
0.05037649366568667
0.04937058167466965
0.04912024321902565
0.047897202276043986
0.04658233387975395
0.04575158439404703
0.04460213457269372
0.044202159916740716
0.042968864812732335
0.042146701732144264
0.041086903695329226
0.04001605057827483
0.039488010112610876
0.03877543581040757
0.03852571047956719
0.03782356018827485
0.036952205900954445
0.03636132728560591
0.035453706343462454
0.034608593661589075
0.03421795387710803
0.03333472957957832
0.03250636977853505
0.031577289497599845
0.031097901257202454
0.030631740217663888
0.030135328311601435
0.029245924581280825
0.028872480829124858
0.028564338230782395
0.02830132530727712
0.02766015923522482
0.027427166029161176
0.026661254685235627
0.026336656491916983
0.025372923643193792
0.024827264946548855
0.02466354253717274
0.023965370110003305
0.02365754695894578
0.02291605545231532
0.022695223157058325
0.022225917346378483
0.021793306111980763
0.021457179246820484
0.020950232056381003
0.020473729786480224
0.020206280125941806
0.019760844913048015
0.01909025293415706
0.018670116029953603
0.01848340051047333
0.01817298771505239
0.01787633756504003
0.017466732155634726
0.017127548423641607
0.016978494045555043
0.016834370226107818
0.01664096840312452
0.016060282558571122
0.01590265488566985
0.01565972833077573
0.015330981283845621
0.014764425699403826
0.014188241479568911
0.01413099235484572
0.013819428236457381
0.013697570810252933
0.013315868117397421
0.01303918577233149
0.012835428291018478
0.012589128040345145
0.012313298002301942
0.011672276181231294
0.011511062536132077
0.011247317074850244
0.011035606195450028
0.010847159683814892
0.010687828520514272
0.010478212285156083
0.0101570033224442
0.009911760775536146
0.009737471273092166
0.009455568808661413
0.009245251941834988
0.009153677537881483
0.008889317990963964
0.008636756355282486
0.008370238446415908
0.00814740283760801
0.007918755101362706
0.00787100703303242
0.007730270004567826
0.007517353376309546
0.00720614434410128
0.007089469186816198
0.006747946144526771
0.006598148188022018
0.006354153883337627
0.005995957415025045
0.0053793090459489275
0.005094052373263651
0.0026104221489026314
1.9354103987417027e-08
0.0

In [118]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA



def preprocess_features(df_node):
    return df_node.select_dtypes(include=[np.number]).fillna(0)

X_train_clean = preprocess_features(X_train)
X_val_clean = preprocess_features(X_val)
X_test_clean = preprocess_features(X_test)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_clean)
X_val_scaled = scaler.transform(X_val_clean)
X_test_scaled = scaler.transform(X_test_clean)


pca = PCA(n_components=120, random_state=42)
pca_x_train = pca.fit_transform(X_train_scaled)
pca_x_val = pca.transform(X_val_scaled)
pca_x_test = pca.transform(X_test_scaled)

In [191]:

from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=3000,
    learning_rate=0.01,
    l2_leaf_reg=15,
    loss_function="Logloss",
    depth=6,
    eval_metric="AUC",
    auto_class_weights="Balanced",
)

model.fit(
      X=X_train,
      y=y_train,
      eval_set=(X_val, y_val),
      early_stopping_rounds=50,
      use_best_model=True,
      verbose=50,
  )

0:	test: 0.6476821	best: 0.6476821 (0)	total: 74.8ms	remaining: 3m 44s
50:	test: 0.7909177	best: 0.7918638 (33)	total: 1.99s	remaining: 1m 54s
100:	test: 0.8051088	best: 0.8051088 (100)	total: 3.17s	remaining: 1m 30s
150:	test: 0.8092715	best: 0.8107852 (111)	total: 4.21s	remaining: 1m 19s
Stopped by overfitting detector  (50 iterations wait)

bestTest = 0.8107852412
bestIteration = 111

Shrink model to first 112 iterations.

CatBoostClassifier(auto_class_weights='Balanced', depth=6, eval_metric='AUC', iterations=3000, l2_leaf_reg=15, learning_rate=0.01, loss_function='Logloss')

In [213]:
# 1. Получаем вероятности (два столбца: для 0 и для 1)
y_probs = model.predict_proba(X_test)[:, 1]
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix, recall_score

results = []

for threshold in np.arange(0.00, 0.75, 0.02):
    y_pred_c = (y_probs >= threshold).astype(int)
    acc = accuracy_score(y_test, y_pred_c)
    recall = recall_score(y_test, y_pred_c)
    precision = precision_score(y_test, y_pred_c)
    f1_micro = f1_score(y_test, y_pred_c, average="micro")
    f1_macro = f1_score(y_test, y_pred_c, average="macro")
    c_mtrx = confusion_matrix(y_test, y_pred_c)

    best_thr = {
    "threshold_value": threshold,
    "acc": acc,
    "recall": recall,
    "precision": precision,
    "f1_micro": f1_micro,
    "f1_macro": f1_macro,
    }
    results.append(best_thr)

df_res = pd.DataFrame(results)

df_res.to_markdown()

/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/dmitrii/catboost_avito/.venv/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

'|    |   threshold_value |      acc |    recall |   precision |   f1_micro |   f1_macro |\n|---:|------------------:|---------:|----------:|------------:|-----------:|-----------:|\n|  0 |              0    | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  1 |              0.02 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  2 |              0.04 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  3 |              0.06 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  4 |              0.08 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  5 |              0.1  | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  6 |              0.12 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  7 |              0.14 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  8 |              0.16 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n|  9 |              0.18 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n| 10 |              0.2  | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n| 11 |              0.22 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n| 12 |              0.24 | 0.193548 | 1         |    0.193548 |   0.193548 |   0.162162 |\n| 13 |              0.26 | 0.204301 | 1         |    0.195652 |   0.204301 |   0.176794 |\n| 14 |              0.28 | 0.215054 | 1         |    0.197802 |   0.215054 |   0.191112 |\n| 15 |              0.3  | 0.247312 | 1         |    0.204545 |   0.247312 |   0.232311 |\n| 16 |              0.32 | 0.274194 | 1         |    0.210526 |   0.274194 |   0.264822 |\n| 17 |              0.34 | 0.295699 | 1         |    0.215569 |   0.295699 |   0.289766 |\n| 18 |              0.36 | 0.333333 | 1         |    0.225    |   0.333333 |   0.331401 |\n| 19 |              0.38 | 0.397849 | 1         |    0.243243 |   0.397849 |   0.39778  |\n| 20 |              0.4  | 0.44086  | 0.944444  |    0.25     |   0.44086  |   0.437674 |\n| 21 |              0.42 | 0.462366 | 0.944444  |    0.257576 |   0.462366 |   0.457283 |\n| 22 |              0.44 | 0.548387 | 0.916667  |    0.289474 |   0.548387 |   0.530811 |\n| 23 |              0.46 | 0.607527 | 0.916667  |    0.320388 |   0.607527 |   0.580758 |\n| 24 |              0.48 | 0.666667 | 0.833333  |    0.348837 |   0.666667 |   0.621902 |\n| 25 |              0.5  | 0.731183 | 0.75      |    0.397059 |   0.731183 |   0.666332 |\n| 26 |              0.52 | 0.752688 | 0.638889  |    0.410714 |   0.752688 |   0.667857 |\n| 27 |              0.54 | 0.77957  | 0.472222  |    0.435897 |   0.77957  |   0.657643 |\n| 28 |              0.56 | 0.801075 | 0.25      |    0.473684 |   0.801075 |   0.605277 |\n| 29 |              0.58 | 0.827957 | 0.166667  |    0.75     |   0.827957 |   0.587583 |\n| 30 |              0.6  | 0.817204 | 0.0833333 |    0.75     |   0.817204 |   0.523795 |\n| 31 |              0.62 | 0.817204 | 0.0555556 |    1        |   0.817204 |   0.501733 |\n| 32 |              0.64 | 0.811828 | 0.0277778 |    1        |   0.811828 |   0.474788 |\n| 33 |              0.66 | 0.806452 | 0         |    0        |   0.806452 |   0.446429 |\n| 34 |              0.68 | 0.806452 | 0         |    0        |   0.806452 |   0.446429 |\n| 35 |              0.7  | 0.806452 | 0         |    0        |   0.806452 |   0.446429 |\n| 36 |              0.72 | 0.806452 | 0         |    0        |   0.806452 |   0.446429 |\n| 37 |              0.74 | 0.806452 | 0         |    0        |   0.806452 |   0.446429 |'

In [34]:
def predict(source_mc_id: int, title: str, description: str, bert_model):
    row = {
    "sourceMcId": source_mc_id,
    "desc_words_count": len(description.split()),
    "desc_length": len(description),
    "has_bull_markers": has_bull_markers(description),
    "has_slashes": has_slash(description),
    "slash_counted": slash_counter(description),
    "paragraph_counted": paragraph_counter(description),
    "turnkey_count": turkney_count(description),
}
    sep = "[SEP]"
    sentence = [f"{title + sep + description}"]
    embeddings = bert_model.encode(sentences=sentence)
    arr = np.vstack(embeddings)

    pred_df_with_embeds = pd.DataFrame(data=arr).add_prefix("embeds")
    final_to_pred = pd.concat((pd.DataFrame([row]), pred_df_with_embeds), axis=1)
    return model.predict_proba(final_to_pred)

In [18]:
import pandas as pd
from catboost import Pool

description = "Ремонт любой сложности!!! / замена фреона / ремонт компрессора / замена термостата / выезд на дом / гарантия 12 месяцев / чек / запчасти в наличии."
source_mc_title = "Ремонт квартир и домов под ключ"

predict(title=source_mc_title, description=description, bert_model=bert_model, source_mc_id=101)

array([[0.76853747, 0.23146253]])

In [ ]:
print("=== Колонки X_train ===")
print(f"Всего: {len(X_train.columns)}")
print(f"Первые 15: {list(X_train.columns[:15])}")
print(f"Последние 5: {list(X_train.columns[-5:])}")

In [35]:
# Тест 1: Максимальный семантический разрыв + Структурные триггеры
# (Тут и разный смысл, и много слов, и слэши, и слово-триггер "отдельно")
title_1 = "Ремонт холодильников"
description_1 = (
    "Ремонт холодильников любой сложности на дому. / "
    "Отдельно предлагаю услуги по дрессировке собак и выгулу домашних животных. / "
    "Также занимаюсь продажей запчастей для тракторов."
)

# Тест 2: Твой кейс с напольными покрытиями, но "дожатый" по объему
# (Если короткий вариант не сработал, этот должен из-за веса фичи desc_length)
title_2 = "Напольные покрытия"
description_2 = (
    "Укладка ламината, кварцвинила и паркетной доски быстро и качественно. "
    "Также выполняем полный монтаж перегородок из гипсокартона, возведение стен и перепланировку. "
    "Отдельно возможна установка натяжных потолков во всей квартире. Звоните!"
)

# Тест 3: Чистый "Винегрет" (много слэшей и разных ниш)
title_3 = "Услуги сантехника"
description_3 = "Установка крана / Ремонт стиральных машин / Поклейка обоев / Перевозка мебели / Грузчики"

# Функция для запуска тестов
def run_tests():
    for i, (t, d) in enumerate([(title_1, description_1), (title_2, description_2), (title_3, description_3)], 1):
        # source_mc_id берем из твоей категории (например, 101 или 109)
        res = predict(title=t, description=d, bert_model=bert_model, source_mc_id=101)
        print(f"Тест {i}: [No Split, Split] -> {res}")

run_tests()

Тест 1: [No Split, Split] -> [[0.65988039 0.34011961]]
Тест 2: [No Split, Split] -> [[0.42415261 0.57584739]]
Тест 3: [No Split, Split] -> [[0.57071159 0.42928841]]

In [98]:
import matplotlib.pyplot as plt
fi = model.get_feature_importance(prettified=True)
print(fi.head(10))

  Feature Id  Importances
0  embeds221     4.351077
1  embeds304     3.391322
2  embeds183     3.248544
3  embeds260     3.115775
4   embeds42     2.836069
5  embeds230     2.601932
6  embeds192     2.300962
7   embeds28     2.029416
8  embeds234     2.024211
9  embeds298     2.021510